# This file tests networks created by learn.py on a dataset created by sampler.py




# This import is regarding [38e732]
import argparse

# pathlib: [889500]
import pathlib

# "chainer" reference: [170ecf]
import chainer

import common
import networks


argumentParser = argparse.ArgumentParser()
argumentParser.add_argument("networkPath",
                            type=str,
                            help="Path where the network parameters are saved; this should be for \
                            a network found in networks.py")
argumentParser.add_argument("datasetPath",
                            type=str,
                            help="Testing dataset's location on disk (the dataset generated by \
                            sampler.py)")
argumentParser.add_argument("settingsPath",
                            type=str,
                            help="Where the training settings were saved")
arguments = argumentParser.parse_args()

chainer.global_config.train = False

network = common.recreateNetwork(arguments.networkPath, arguments.settingsPath)
dataset = common.shapeDataset(arguments.datasetPath)

print(common.performance(network, dataset))
